export const DOJ_TRANCHE_OPTIONS: Array<{ value: string; label: string; sources: string[] }> = [
  { value: 'all', label: 'All tranches', sources: [] },
  { value: 'black-book', label: 'Unredacted Black Book', sources: ['Unredacted Black Book'] },
  { value: 'flight-logs', label: 'Flight Logs', sources: ['Flight Logs'] },
  { value: 'birthday-book', label: 'Birthday Book', sources: ['Birthday Book'] },
  {
    value: 'estate-emails',
    label: 'Estate Emails (2009-2019)',
    sources: ['Epstein Estate Documents - Seventh Production'],
  },
  { value: 'court-case-evidence', label: 'Court Case Evidence', sources: ['Court Case Evidence'] },
  { value: 'maxwell-proffer', label: 'Maxwell Proffer', sources: ['Maxwell Proffer'] },
  {
    value: 'doj-discovery-vol1',
    label: 'DOJ Discovery (VOL00001)',
    sources: ['DOJ Discovery VOL00001'],
  },
  {
    value: 'doj-discovery-vol2-8',
    label: 'DOJ Discovery (VOL00002-8)',
    sources: [
      'DOJ Discovery VOL00002',
      'DOJ Discovery VOL00003',
      'DOJ Discovery VOL00004',
      'DOJ Discovery VOL00005',
      'DOJ Discovery VOL00006',
      'DOJ Discovery VOL00007',
      'DOJ Discovery VOL00008',
    ],
  },
  {
    value: 'doj-dataset-9-11',
    label: 'DOJ Data Set 9-11',
    sources: ['DOJ Data Set 9', 'DOJ Data Set 10', 'DOJ Data Set 11'],
  },
  {
    value: 'doj-dataset-9-12',
    label: 'DOJ Data Sets 9-12',
    sources: ['DOJ Data Set 9', 'DOJ Data Set 10', 'DOJ Data Set 11', 'DOJ Data Set 12'],
  },
  { value: 'doj-dataset-9', label: 'DOJ Data Set 9', sources: ['DOJ Data Set 9'] },
  { value: 'doj-dataset-10', label: 'DOJ Data Set 10', sources: ['DOJ Data Set 10'] },
  { value: 'doj-dataset-11', label: 'DOJ Data Set 11', sources: ['DOJ Data Set 11'] },
  { value: 'doj-dataset-12', label: 'DOJ Data Set 12', sources: ['DOJ Data Set 12'] },
  {
    value: 'doj-discovery',
    label: 'DOJ Discovery Volumes',
    sources: [
      'DOJ Discovery VOL00001',
      'DOJ Discovery VOL00002',
      'DOJ Discovery VOL00003',
      'DOJ Discovery VOL00004',
      'DOJ Discovery VOL00005',
      'DOJ Discovery VOL00006',
      'DOJ Discovery VOL00007',
      'DOJ Discovery VOL00008',
    ],
  },
  { value: 'evidence-images', label: 'Evidence Images', sources: ['Evidence Images'] },
  { value: 'doj-phase-1', label: 'DOJ Phase 1', sources: ['DOJ Phase 1'] },
];
