/* eslint-disable no-undef */

export async function up(pgm) {
  pgm.sql(`
    CREATE TABLE IF NOT EXISTS global_timeline_events (
      id BIGSERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      date DATE NOT NULL,
      description TEXT,
      type TEXT DEFAULT 'other',
      significance TEXT DEFAULT 'medium',
      entities TEXT,
      related_document_id BIGINT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      source TEXT
    );

    CREATE INDEX IF NOT EXISTS idx_global_timeline_events_date ON global_timeline_events(date);
    CREATE INDEX IF NOT EXISTS idx_global_timeline_events_type ON global_timeline_events(type);
  `);

  pgm.sql(`INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(25,'First Overlap in NYC Money Scene','1987-01-01','Trump and Epstein begin spending winters in Palm Beach. Alan Dershowitz quipped you were ''a nobody'' if you didn''t know them.','other','medium','[3,1,21]',NULL,'2026-01-06 01:36:14','Business Insider') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(26,'Epstein Buys Palm Beach Mansion','1990-01-01','Epstein buys a mansion two miles from Mar-a-Lago, tightening the social loop between him and Trump.','other','medium','[3,1]',NULL,'2026-01-06 01:36:14','Business Insider') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(27,'Mar-a-Lago Party Footage','1992-11-01','NBC cameras capture Trump and Epstein ogling NFL cheerleaders at a ''bachelor life'' party in Mar-a-Lago. Footage later airs in 2019.','incident','high','[3,1]',NULL,'2026-01-06 01:36:14','The Guardian') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(28,'Calendar-Girls Party','1992-11-15','Organiser George Houraney says only two men showed—Trump and Epstein—plus 28 models.','incident','high','[3,1]',NULL,'2026-01-06 01:36:14','Business Insider') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(29,'Multiple Photos Together','1997-01-01','Multiple photos show Trump and Epstein together in Palm Beach and at a Victoria''s Secret after-party in NYC.','other','medium','[3,1]',NULL,'2026-01-06 01:36:14','Business Insider') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(30,'Maxwell & Giuffre Threads','1999-01-01','Virginia Giuffre testifies she was recruited at Mar-a-Lago in 1999. Ghislaine Maxwell often seen in photos with Trump/Epstein.','legal','high','[3,2,48,1]',NULL,'2026-01-06 01:36:15','Business Insider') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(31,'Epstein Brags About Melania Introduction','1998-01-01','Epstein brags he introduced Trump to Melania; unverified but often repeated in investigative reports.','other','medium','[3,1,151]',NULL,'2026-01-06 01:36:15','Business Insider') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(32,'Little Black Book & Flight Logs','1997-01-01','Epstein''s ''little black book'' lists 14 Trump-related numbers; Trump flies at least once on Epstein''s 727, per flight logs.','other','high','[3,1]',NULL,'2026-01-06 01:36:15','Business Insider') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(33,'Real-Estate Showdown (Maison de l''Amitié)','2004-01-01','Bankruptcy auction: Trump and Epstein wage a bidding war; Trump wins at ~$41 million. This feuded eventually killed the friendship.','financial','high','[3,1]',NULL,'2026-01-06 01:36:15','Washington Post') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(34,'Mar-a-Lago Ban','2007-01-01','Attorneys for Epstein''s victims later state Trump banned Epstein from the club after hearing Epstein ''sexually assaulted an underage girl'' on-site.','incident','high','[3,1]',NULL,'2026-01-06 01:36:15','The Washington Post') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(35,'Police Investigation & ''Sweetheart'' Plea','2005-01-01','Palm Beach police open a case in 2005; by 2008 Epstein cuts a federal non-prosecution deal brokered by Alex Acosta.','legal','high','[1,9812]',NULL,'2026-01-06 01:36:15','The Washington Post') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(36,'Trump Helps Accusers','2009-01-01','Victims'' lawyer Brad Edwards says Trump was ''the only person who picked up the phone'' and offered information in 2009.','legal','high','[3,48,1]',NULL,'2026-01-06 01:36:15','Washington Post') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(37,'Trump''s Public Denials','2019-07-09','Asked about Epstein''s arrest, Trump says he hasn''t spoken to him ''in 15 years'' and ''was not a fan.''','other','medium','[3,1]',NULL,'2026-01-06 01:36:15','Washington Post') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(38,'Epstein''s Death','2019-08-10','Epstein dies by suicide in a federal jail; DOJ IG (2023) re-affirms suicide finding.','incident','high','[1]',NULL,'2026-01-06 01:36:15','DOJ Inspector General') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(39,'Maxwell Conviction','2021-12-29','Maxwell convicted of sex-trafficking minors; sentenced to 20 years in federal prison.','legal','high','[2]',NULL,'2026-01-06 01:36:15','Federal Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(40,'Wolff Tapes Released','2024-11-01','Michael Wolff releases 2017 audio of Epstein boasting he was Trump''s ''closest friend''. Trump''s camp calls it ''pure fiction.''','incident','high','[42,3,1]',NULL,'2026-01-06 01:36:15','The Guardian') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(41,'Phase 1 File Release','2025-02-27','AG Pam Bondi declassifies a thin batch of files related to the Epstein investigation. MAGA influencers call it a ''nothing-burger.''','legal','high','[1]',NULL,'2026-01-06 01:36:15','The Washington Post') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(42,'Elon Musk''s Claims','2025-06-06','Elon Musk claims ''Trump is in the secret Epstein files''—though no evidence is provided.','other','medium','[18,3]',NULL,'2026-01-06 01:36:15','Business Insider') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(43,'DOJ/FBI Memo','2025-07-01','Concludes there is no ''client list,'' no evidence Trump was extorted, and Epstein died by suicide.','legal','high','[3,1]',NULL,'2026-01-06 01:36:15','Axios, DOJ') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(44,'House Democrats'' Demand','2025-07-08','Jamie Raskin & Dan Goldman accuse DOJ of shielding Trump; demand unredacted files.','legal','medium','[3]',NULL,'2026-01-06 01:36:15','The Guardian') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(45,'MAGA Backlash','2025-07-09','Pro-Trump influencers turn on Bondi, alleging a cover-up. Trump urges focus on ''real scandals.''','incident','medium','[3]',NULL,'2026-01-06 01:36:15','Politico') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(46,'Final DOJ Statement','2025-07-10','DOJ says no further releases planned; watchdogs vow FOIA suits.','legal','medium','[1]',NULL,'2026-01-06 01:36:15','Business Insider') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(47,'Documentary: epstein harmed over 1,000 victims but no ''client list''','2024-01-01','Coffeezilla-style breakdown of the newly leaked FBI/DOJ memo: it confirms Epstein abused well over 1,000 victims, yet the Bureau says no ''client list'' exists.','other','high','[1,3]',NULL,'2026-01-06 01:36:15','voidzilla (YouTube)') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(48,'Investigation: new epstein footage is a disaster','2024-02-01','Dissects the 10-hour prison-cell video released by DOJ. Highlights a mysterious 60-second blackout and camera switch-overs.','incident','high','[1]',NULL,'2026-01-06 01:36:15','voidzilla (YouTube)') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(49,'Epstein Document Release - First Batch','2024-01-03','Federal court releases first batch of previously sealed documents from Ghislaine Maxwell civil case, naming prominent figures.','legal','high','["Ghislaine Maxwell","Bill Clinton","Prince Andrew"]',NULL,'2026-01-20 10:39:57','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(50,'Second Document Release','2024-01-08','Additional court documents released containing flight logs, depositions, and witness testimonies.','legal','high','["Jeffrey Epstein","Ghislaine Maxwell"]',NULL,'2026-01-20 10:39:57','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(51,'Prince Andrew Settlement Details Emerge','2024-02-15','New details emerge about Prince Andrew settlement with Virginia Giuffre, reportedly exceeding $12 million.','legal','high','["Prince Andrew","Virginia Giuffre"]',NULL,'2026-01-20 10:39:57','Media Reports') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(52,'JPMorgan Settles Epstein Victim Lawsuits','2024-03-20','JPMorgan Chase reaches $290 million settlement with Epstein victims over facilitating his activities.','financial','high','["JPMorgan Chase","Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Court Settlement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(53,'New Flight Log Analysis Published','2024-04-12','Independent researchers publish comprehensive analysis of all known Epstein flight logs, identifying new patterns.','other','medium','["Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Research Publication') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(54,'Ghislaine Maxwell Appeal Denied','2024-06-28','Federal appeals court denies Ghislaine Maxwell bid to overturn her sex trafficking conviction.','legal','high','["Ghislaine Maxwell"]',NULL,'2026-01-20 10:39:57','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(55,'Deutsche Bank Settlement','2024-07-15','Deutsche Bank reaches $75 million settlement with Epstein accusers for handling his accounts.','financial','high','["Deutsche Bank","Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Court Settlement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(56,'New Documentary Release: "Epstein Files"','2024-08-20','Major streaming platform releases documentary with new interviews from victims and investigators.','other','medium','["Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Media') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(57,'US Virgin Islands Settlement Finalized','2024-09-10','USVI Attorney General finalizes $105 million settlement from Epstein estate for victims fund.','legal','high','["Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Government Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(58,'Additional Documents Unsealed','2024-10-15','Court releases additional unsealed documents from various civil suits, revealing more names.','legal','high','["Jeffrey Epstein","Ghislaine Maxwell"]',NULL,'2026-01-20 10:39:57','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(59,'Jean-Luc Brunel Death Investigation Reopened','2024-11-22','French authorities reopen investigation into the prison death of modeling agent Jean-Luc Brunel.','legal','medium','["Jean-Luc Brunel","Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Law Enforcement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(60,'Year-End Document Compilation Released','2024-12-30','Comprehensive compilation of all 2024 released documents made publicly available.','legal','medium','["Jeffrey Epstein","Ghislaine Maxwell"]',NULL,'2026-01-20 10:39:57','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(61,'New Grand Jury Investigation Announced','2025-01-15','Federal prosecutors announce new grand jury investigation into potential co-conspirators.','legal','high','["Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','DOJ Announcement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(62,'Victim Compensation Fund Reaches $500M','2025-02-28','Total compensation to victims from all sources reaches half billion dollars milestone.','financial','high','["Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Fund Administration') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(63,'Little St. James Island Sale Completed','2025-03-15','Epstein estate completes sale of Little St. James island, proceeds directed to victim fund.','financial','high','["Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Estate Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(64,'Congressional Hearing on DOJ Handling','2025-04-22','House Judiciary Committee holds hearing examining DOJ handling of original Epstein investigation.','legal','high','["Jeffrey Epstein","Alexander Acosta"]',NULL,'2026-01-20 10:39:57','Congressional Record') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(65,'New Witness Testimony Released','2025-05-18','Previously sealed witness depositions from civil cases made public, revealing new details.','testimony','high','["Jeffrey Epstein","Ghislaine Maxwell"]',NULL,'2026-01-20 10:39:57','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(66,'International Investigation Coordination','2025-06-30','US, UK, and France announce coordinated effort to investigate international trafficking network.','legal','high','["Jeffrey Epstein","Jean-Luc Brunel"]',NULL,'2026-01-20 10:39:57','Law Enforcement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(67,'Maxwell Parole Hearing Scheduled','2025-08-01','First parole hearing for Ghislaine Maxwell scheduled for review.','legal','medium','["Ghislaine Maxwell"]',NULL,'2026-01-20 10:39:57','Prison Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(68,'New Academic Study on Network Analysis','2025-09-15','University researchers publish comprehensive social network analysis of Epstein contacts.','other','medium','["Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Academic Publication') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(69,'Additional Civil Suits Filed','2025-10-20','New wave of civil suits filed against estates and remaining defendants.','legal','medium','["Jeffrey Epstein"]',NULL,'2026-01-20 10:39:57','Court Filings') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(70,'FBI Files Partial Release','2025-11-30','FBI releases partial files from Epstein investigation under FOIA request.','legal','high','["Jeffrey Epstein","FBI"]',NULL,'2026-01-20 10:39:57','FOIA Release') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(71,'5-Year Anniversary of Maxwell Conviction','2025-12-29','Media retrospectives mark five years since Maxwell conviction, survivors share updates.','other','medium','["Ghislaine Maxwell"]',NULL,'2026-01-20 10:39:57','Media') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(72,'New Presidential Administration Review','2026-01-20','New administration announces review of all federal handling of Epstein-related matters.','legal','high','["Jeffrey Epstein","DOJ"]',NULL,'2026-01-20 10:39:57','Executive Action') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(73,'Epstein Document Release - First Batch','2024-01-03','Federal court releases first batch of previously sealed documents from Ghislaine Maxwell civil case, naming prominent figures.','legal','high','["Ghislaine Maxwell","Bill Clinton","Prince Andrew"]',NULL,'2026-01-20 11:12:26','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(74,'Second Document Release','2024-01-08','Additional court documents released containing flight logs, depositions, and witness testimonies.','legal','high','["Jeffrey Epstein","Ghislaine Maxwell"]',NULL,'2026-01-20 11:12:26','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(75,'Prince Andrew Settlement Details Emerge','2024-02-15','New details emerge about Prince Andrew settlement with Virginia Giuffre, reportedly exceeding $12 million.','legal','high','["Prince Andrew","Virginia Giuffre"]',NULL,'2026-01-20 11:12:26','Media Reports') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(76,'JPMorgan Settles Epstein Victim Lawsuits','2024-03-20','JPMorgan Chase reaches $290 million settlement with Epstein victims over facilitating his activities.','financial','high','["JPMorgan Chase","Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Court Settlement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(77,'New Flight Log Analysis Published','2024-04-12','Independent researchers publish comprehensive analysis of all known Epstein flight logs, identifying new patterns.','other','medium','["Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Research Publication') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(78,'Ghislaine Maxwell Appeal Denied','2024-06-28','Federal appeals court denies Ghislaine Maxwell bid to overturn her sex trafficking conviction.','legal','high','["Ghislaine Maxwell"]',NULL,'2026-01-20 11:12:26','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(79,'Deutsche Bank Settlement','2024-07-15','Deutsche Bank reaches $75 million settlement with Epstein accusers for handling his accounts.','financial','high','["Deutsche Bank","Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Court Settlement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(80,'New Documentary Release: "Epstein Files"','2024-08-20','Major streaming platform releases documentary with new interviews from victims and investigators.','other','medium','["Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Media') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(81,'US Virgin Islands Settlement Finalized','2024-09-10','USVI Attorney General finalizes $105 million settlement from Epstein estate for victims fund.','legal','high','["Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Government Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(82,'Additional Documents Unsealed','2024-10-15','Court releases additional unsealed documents from various civil suits, revealing more names.','legal','high','["Jeffrey Epstein","Ghislaine Maxwell"]',NULL,'2026-01-20 11:12:26','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(83,'Jean-Luc Brunel Death Investigation Reopened','2024-11-22','French authorities reopen investigation into the prison death of modeling agent Jean-Luc Brunel.','legal','medium','["Jean-Luc Brunel","Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Law Enforcement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(84,'Year-End Document Compilation Released','2024-12-30','Comprehensive compilation of all 2024 released documents made publicly available.','legal','medium','["Jeffrey Epstein","Ghislaine Maxwell"]',NULL,'2026-01-20 11:12:26','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(85,'New Grand Jury Investigation Announced','2025-01-15','Federal prosecutors announce new grand jury investigation into potential co-conspirators.','legal','high','["Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','DOJ Announcement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(86,'Victim Compensation Fund Reaches $500M','2025-02-28','Total compensation to victims from all sources reaches half billion dollars milestone.','financial','high','["Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Fund Administration') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(87,'Little St. James Island Sale Completed','2025-03-15','Epstein estate completes sale of Little St. James island, proceeds directed to victim fund.','financial','high','["Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Estate Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(88,'Congressional Hearing on DOJ Handling','2025-04-22','House Judiciary Committee holds hearing examining DOJ handling of original Epstein investigation.','legal','high','["Jeffrey Epstein","Alexander Acosta"]',NULL,'2026-01-20 11:12:26','Congressional Record') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(89,'New Witness Testimony Released','2025-05-18','Previously sealed witness depositions from civil cases made public, revealing new details.','testimony','high','["Jeffrey Epstein","Ghislaine Maxwell"]',NULL,'2026-01-20 11:12:26','Court Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(90,'International Investigation Coordination','2025-06-30','US, UK, and France announce coordinated effort to investigate international trafficking network.','legal','high','["Jeffrey Epstein","Jean-Luc Brunel"]',NULL,'2026-01-20 11:12:26','Law Enforcement') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(91,'Maxwell Parole Hearing Scheduled','2025-08-01','First parole hearing for Ghislaine Maxwell scheduled for review.','legal','medium','["Ghislaine Maxwell"]',NULL,'2026-01-20 11:12:26','Prison Records') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(92,'New Academic Study on Network Analysis','2025-09-15','University researchers publish comprehensive social network analysis of Epstein contacts.','other','medium','["Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Academic Publication') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(93,'Additional Civil Suits Filed','2025-10-20','New wave of civil suits filed against estates and remaining defendants.','legal','medium','["Jeffrey Epstein"]',NULL,'2026-01-20 11:12:26','Court Filings') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(94,'FBI Files Partial Release','2025-11-30','FBI releases partial files from Epstein investigation under FOIA request.','legal','high','["Jeffrey Epstein","FBI"]',NULL,'2026-01-20 11:12:26','FOIA Release') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(95,'5-Year Anniversary of Maxwell Conviction','2025-12-29','Media retrospectives mark five years since Maxwell conviction, survivors share updates.','other','medium','["Ghislaine Maxwell"]',NULL,'2026-01-20 11:12:26','Media') ON CONFLICT (id) DO NOTHING;
INSERT INTO global_timeline_events (id, title, date, description, type, significance, entities, related_document_id, created_at, source) VALUES(96,'New Presidential Administration Review','2026-01-20','New administration announces review of all federal handling of Epstein-related matters.','legal','high','["Jeffrey Epstein","DOJ"]',NULL,'2026-01-20 11:12:26','Executive Action') ON CONFLICT (id) DO NOTHING;
`);

  pgm.sql(
    `SELECT setval(pg_get_serial_sequence('global_timeline_events', 'id'), COALESCE((SELECT MAX(id) FROM global_timeline_events), 1), true);`,
  );
}

export async function down(_pgm) {
  // Historical prod data restoration. Intentionally no-op.
}
