// Aggressive Entity Filters
// Purpose: Block junk entities, OCR artifacts, and common non-entity phrases from entering the database.

const JUNK_PHRASES = new Set([
  'search personnel',
  'epstein merwin dela',
  'is read',
  'start date',
  'unknown',
  'search completed',
  'employee name',
  'trust agreement',
  'initials search',
  'health concerns',
  'red hook quarters',
  'emergency contact',
  'treatment cooling',
  'little st',
  'the settlor',
  'white pls',
  'substituted property',
  'central ohio insur...',
  'margaret girard',
  'substitution powe',
  'cooling tower',
  'marital status',
  'jugglers beach',
  'date of birth',
  'social security',
  'drivers license',
  'passport number',
  'telephone number',
  'fax number',
  'email address',
  'website',
  'page',
  'page of',
  'exhibit',
  'attachment',
  'confidential',
  'privileged',
  'attorney work product',
  'draft',
  'final',
  'copy',
  'original',
  'certified',
  'notary public',
  'sworn to',
  'subscribed',
  'affidavit',
  'deposition',
  'testimony',
  'plaintiff',
  'defendant',
  'v.',
  'vs.',
  'et al',
  'united states',
  'district court',
  'supreme court',
  'court of appeals',
  'department of justice',
  'fbi',
  'federal bureau',
  'cia',
  'central intelligence',
  'irs',
  'internal revenue',
  'sec',
  'securities and exchange',
  'new york',
  'los angeles',
  'palm beach',
  'paris',
  'london',
  'virgin islands',
  'st. james',
  'little st. james',
  'great st. james',
  // 'zorro', // Removed to allow codename detection
  'je',
  'gm',
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
  'january',
  'february',
  'march',
  'april',
  'may',
  'june',
  'july',
  'august',
  'september',
  'october',
  'november',
  'december',
  'total',
  'subtotal',
  'grand total',
  'balance',
  'due',
  'paid',
  'invoice',
  'receipt',
  'account',
  'bank',
  'check',
  'credit card',
  'wire transfer',
  'cash',
  'flight',
  'aircraft',
  'pilot',
  'passenger',
  'arrival',
  'departure',
  'hotel',
  'room',
  'suite',
  'reservation',
  'booking',
  'message',
  'call',
  'meeting',
  'appointment',
  'schedule',
  'calendar',
  'memo',
  'memorandum',
  'letter',
  'note',
  'report',
  'summary',
  'subject',
  're',
  'fw',
  'fwd',
  'cc',
  'bcc',
  'to',
  'from',
  'mr',
  'ms',
  'mrs',
  'dr',
  'prof',
  'hon',
  'esq',
  'jr',
  'sr',
  'ii',
  'iii',
  'iv',
  'inc',
  'llc',
  'ltd',
  'corp',
  'corporation',
  'company',
  'partners',
  'associates',
  'foundation',
  'trust',
  'charity',
  'organization',
  'association',
  'society',
  'university',
  'college',
  'school',
  'academy',
  'institute',
  'hospital',
  'clinic',
  'center',
  'medical',
  'health',
  'street',
  'avenue',
  'road',
  'boulevard',
  'lane',
  'drive',
  'way',
  'place',
  'square',
  'park',
  'north',
  'south',
  'east',
  'west',
  'apt',
  'suite',
  'unit',
  'floor',
  'building',
  'tower',
  'plaza',
  'box',
  'po box',
  'city',
  'state',
  'zip',
  'country',
  'usa',
  'uk',
  'us',
  'ny',
  'ca',
  'fl',
  'vi',
  'nm',
  // New Junk Additions (2026-01-06)
  'search personnel name',
  'central ohio insurance',
  'legionella water testing',
  'emergency contact',
  'no is invitation',
  'yes is invitation',
  'monthly maintenance',
  'substitution power',
  'american express',
  'colonial bank',
  'atlas obscura',
  'cleaning cleaning',
  'little saint james',
  'james island ares',
  'initials search completed',
  'agency contact number',
  'treatment cooling tower',
  'search completed',
  'employee name',
  'trust agreement',
  'health concerns',
  'red hook quarters',
  'substituted property',
  'white pls',
  'margaret girard',
  'jugglers beach',
  'marital status',
  'social security',
  'date of birth',
  'drivers license',
  'white house',
  'they like',
  'judge printed',
  'multiple mac desktops',
  'closed contaisensitems contained',
  'other additions',
  'other structures',
  'tiered interest',
  'your advantage',
  'multiple he towers',
  'little st james', // Often better as Location, but if appearing as Person name, block matches
]);

const JUNK_REGEX = [
  /^\d+$/, // All numbers
  /^\W+$/, // All non-word characters
  /^.{0,3}$/, // Very short strings (Ag, Ed, Al are exceptions but usually better to strict filter in automated runs)
  /\d{3,}/, // Contains 3+ consecutive numbers (often phone numbers or zip codes)
  /^[a-z]/, // Starts with lowercase (names are Capitalized)
  /[\[\]\(\)\{\}]/, // Contains brackets/parentheses
  /http|www|\.com|\.net|\.org/, // URLs/Emails
  /page \d+/i, // Page numbers
  /exhibit \w+/i, // Exhibit labels
  /all rights\s+reserved/i,
  /copyright/i,
  /^they like/i,
  /^judge printed/i,
  /^multiple (mac|he|she|it)/i,
  /^closed contain/i,
  /^estate (of|thomas|jeffrey)/i,
  /new mexico/i,
  /new york times/i,
  /other additions/i,
  /desktop/i,
];

export function isJunkEntity(name: string): boolean {
  if (!name) return true;

  const normalized = name.trim().toLowerCase();

  // 1. Check blacklist
  if (JUNK_PHRASES.has(normalized)) return true;

  // 2. Check regex patterns
  for (const pattern of JUNK_REGEX) {
    if (pattern.test(name)) return true;
  }

  // 3. Check for mostly uppercase (headers) ?
  // Maybe too strict for "FBI", "CIA", etc. but for Person names it's usually mixed case.
  // if (name === name.toUpperCase() && name.length > 4) return true;

  // 4. Check word count. Names are usually 2-3 words.
  const wordCount = normalized.split(/\s+/).length;
  if (wordCount > 4) return true; // "Director of the Board of ..." -> Role, not name.

  return false;
}

export function normalizeName(name: string): string {
  return name.trim().replace(/\s+/g, ' ');
}
